### ISSUE TITLE
Repositories script doesn't recognize license correctly

### ISSUE THREAD

**Issue by hugosolar** [creativecommons/ccos-scripts#81]
## Description
The script that gather informations from CC repositories doesn't recognize some repo licenses
for instance:
- https://github.com/creativecommons/wp-theme-base
- https://github.com/creativecommons/wp-theme-openglam
- https://github.com/creativecommons/wp-theme-summit

## Reproduction
1. go to [Open Source project list](https://opensource.creativecommons.org/contributing-code/projects/)
2. Check out `wp-theme-summit` at the bottom of the list. it says "GNU General Public License v2.0"
3. Check the MIT license in the [repo](https://github.com/creativecommons/wp-theme-summit)

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by avats-dev** [comment]
I checked https://github.com/creativecommons/ccos-scripts/blob/master/push_data_to_ccos/get_repo_data.py and it works fine, so there must be something wrong in the process of pushing code to the [website repo](https://github.com/creativecommons/creativecommons.github.io-source). I saw that there was a similar thing in all of the discrepancies that are present on the [projects page](https://opensource.creativecommons.org/contributing-code/projects/) and all of them were edited in some sort 6 days ago and the **workflow for pushing this data is also failing since 6 days**, so that might be the reason for this.

This is a part of the log from the failed action (6 days ago), and this mentions the error. The error is same for all the failures, i.e. **`authentication failed`**.

```
2020-09-17T01:00:40.7931494Z Cloning repo...
2020-09-17T01:00:40.7932072Z Pulling latest code...
2020-09-17T01:00:40.7932678Z Setting up git user...
2020-09-17T01:00:40.7933301Z Generating JSON file...
2020-09-17T01:00:40.7933947Z Pushing latest code...
2020-09-17T01:00:40.7934809Z Traceback (most recent call last):
2020-09-17T01:00:40.7937295Z   File "sync_data.py", line 32, in <module>
2020-09-17T01:00:40.7938529Z     push_data(source(), f'{databag}.json')
2020-09-17T01:00:40.7940488Z   File "/home/runner/work/ccos-scripts/ccos-scripts/push_data_to_ccos/push_data_via_git.py", line 78, in push_data
2020-09-17T01:00:40.7941712Z     commit_and_push_changes(json_filename)
2020-09-17T01:00:40.7943558Z   File "/home/runner/work/ccos-scripts/ccos-scripts/push_data_to_ccos/push_data_via_git.py", line 69, in commit_and_push_changes
2020-09-17T01:00:40.7944721Z     origin.push()
2020-09-17T01:00:40.7946496Z   File "/home/runner/.local/share/virtualenvs/push_data_to_ccos-BbZwxIuW/lib/python3.7/site-packages/git/remote.py", line 849, in push
2020-09-17T01:00:40.7947923Z     return self._get_push_info(proc, progress)
2020-09-17T01:00:40.7949876Z   File "/home/runner/.local/share/virtualenvs/push_data_to_ccos-BbZwxIuW/lib/python3.7/site-packages/git/remote.py", line 736, in _get_push_info
2020-09-17T01:00:40.7951263Z     proc.wait(stderr=stderr_text)
2020-09-17T01:00:40.7953067Z   File "/home/runner/.local/share/virtualenvs/push_data_to_ccos-BbZwxIuW/lib/python3.7/site-packages/git/cmd.py", line 408, in wait
2020-09-17T01:00:40.7954651Z     raise GitCommandError(self.args, status, errstr)
2020-09-17T01:00:40.7956197Z git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
2020-09-17T01:00:40.7957502Z   cmdline: git push --porcelain origin
2020-09-17T01:00:40.7959782Z   stderr: 'fatal: Authentication failed for 'https://github.com/creativecommons/creativecommons.github.io-source.git/''
2020-09-17T01:00:40.8331548Z ##[error]Process completed with exit code 1.
2020-09-17T01:00:40.8405202Z Post job cleanup.
```
You can see [here](https://github.com/creativecommons/ccos-scripts/actions?query=workflow%3A%22Push+data+to+CC+Open+Source%22) that it has been failing since 6 days.

![Screenshot from 2020-09-23 01-08-57](https://user-images.githubusercontent.com/35889327/93929450-7ff5cd80-fd39-11ea-966b-b1e5eac82396.png)

@kgodey @dhruvkb seems important!

> Related to #82

**Comment by kgodey** [comment]
This was fixed by https://github.com/creativecommons/ccos-scripts/issues/82
